name: "Build and Test"

on: [ push, workflow_dispatch, pull_request ]

jobs:

  higgs-shop-sample-app:
    name: "Check Higgs Shop Sample App"
    uses: mParticle/mparticle-android-sample-apps/.github/workflows/pull-request-app-checks.yml@main
    with:
      app_relative_path: "core-sdk-samples/higgs-shop-sample-app"

  automerge-dependabot:
    name: "Save PR Number for Dependabot Automerge"
    needs: [ higgs-shop-sample-app ]
    uses: mParticle/mparticle-workflows/.github/workflows/dependabot-save-pr-number.yml@main
