name: "Push Checks"

on: [ push, workflow_dispatch ]

jobs:

  higgs-shop-sample-app:
    name: "Check Higgs Shop Sample App"
    uses: mParticle/mparticle-workflows/.github/workflows/android-sample-app-push.yml@stable
    with:
      app_relative_path: "core-sdk-samples/higgs-shop-sample-app"